### ISSUE TITLE
Log suggests Namecheap update is failing

### ISSUE THREAD

**Issue by jmscsns** [CallumWatkins/dynamic-dns-updater#1]
The log suggests that the update has failed, at each run reporting:

```
Getting current public IP address... Done - 123.456.789.012
Performing first time sync.
 - *.example.com... Failed - Response contained invalid or unexpected XML
 - @.example.com... Failed - Response contained invalid or unexpected XML
One or more hosts could not be updated; see above.
```

However, the DNS is updated.

I don't know C# but it seems everything is fine, and the update URL is generated and successfully sent (and therefore updating the DNS), but something in the response is triggering the exception handling in lines 96-100 of NamecheapDDNSUpdater.cs. The response I'm getting is:

```
<?xml version="1.0" encoding="utf-16"?>
<interface-response>
  <Command>SETDNSHOST</Command>
  <Language>eng</Language>
  <IP>123.456.789.012</IP>
  <ErrCount>0</ErrCount>
  <errors />
  <ResponseCount>0</ResponseCount>
  <responses />
  <Done>true</Done>
  <debug><![CDATA[]]></debug>
</interface-response>
```

which seems valid to me.

**Comment by CallumWatkins** [comment]
Thanks for flagging this issue. I've released a fix in v1.0.1.
